export const RESOURCEDATA = [
    {
        id: 0, 
        title: "Crochet Hooks", 
        important: "Crochet hooks are a fundamental tool to the craft. Some may say that without crochet hooks, can one even crochet? Crochet hooks come in all shapes, sizes, colors, and materials. Plus, which hook you choose for a project matters.", 
        content: "\nThe primary differentiation for crochet hooks is size. While material can play an important role in purchasing decisions, it really is just a matter of personal preference. Crochet hook size can be measured in mm, by letter, or by number (with US sizing being different from UK sizing). Every hook will have a mm sizing while not every hook with have a letter or number. The usual size range spans from 2.0mm to 16.0mm with 0.25 or 0.5 increments. 2.0mm is the one of the smaller crochet hooks and is best suited to the lightest yarn weights (e.g. Lace or Thread). On the other hand, 16.00mm is rather large and should be used with the thickest yarn (e.g. Jumbo). Using a hook that is too small may result in you splitting your yarn, which using a hook that is too big may result great difficulty crocheting and large holes in your stitches."
    }, 
    {
        id: 1, 
        title: "All About Yarn", 
        important: "Yarn Weight, used to describe the thickness of a yarn skein, is an important topic to understand. Many patters you will encounter give a reccomended yarn wight (and hook size) for good reason. Yarns typically come in 7 thicknesses that range from the thickness of a thread to almost the thickness of a finger; the amount needed and hook used can vary greatly. Some yarn weights are also easier to work with than others when it comes to beginners: a heavier (thicker) weight tends to be reccomended. It is also good to keep in mind that some wieghts have alternate names (e.g. weight three is also called light)", 
        content: "\nTelling Yarn Weight From Skein Label\nThe most common, and easiest way, to determine yarn weight is to look at the yarns label. Pretty much ever yarn skeins label contains a symbol or description of the skeins wight. A yarn weight symbol is conprised of a skien of yarn with a number overlaid on top of it.\nEach yarn weight also comes with a reccomended hook size (the symbol as a whole refered to as gague). For knitters, there is a similar gague section for knitting needles. For example, it would not make much sense to use a teeny-tiny hook on jumbo yarn. This symbol is typically located near or next to the yarn weight indicator. The symbol itself consists of a picture of a crochet hook, the hook size in milimeters and US size, and numbers along the left and top side that indicate the size of the gague square. The numbers along the right and bottom of the square indicate how many rows and stitches the gague sqaure comprises of. Gague squares are used to help crafters understand how large/small/tight/loose their sitiches should be for a pattern.\n\nTelling Yarn Weight Without A Label\nNow having a label to tell you a yarns weight is all well and good, but what happens if the label is missing? Most crocheters and knitters then use a method called Wraps Per Inch. This method requires a ruler, the mystery yarn, and (optionally) an object with a consistent circumfrence.To calculate the weight, simply wrap the yarn around an inch of your obejct (or ruler) counting the number of wraps. It is better to wrap a little tighter since you do not want to leave gaps or loose pockets. Once you have the number of wraps, simply match it to the standard number of wraps for a yarn weight."
    },
    {
        id: 2, 
        title: "Books For Beginners", 
        important: "Learning to crochet can seem dauting at first with all the new terminology, stitch types, and trying to read patterns. Books aimed at novice crocheters can help to clarify understanding by presenting the needed information in a cronological, succint, and simple manner. Books also act as a great reference thoughout one's crochet journey by acting as a knowledge store and keeping crocheters from having to memeorize large amounts of infomration they use rarely.  ", 
        content: "\nSome of the most popular books for those just starting to crochet include:\n\nA to Z of Crochet\nThis books starts at the very beginning level (i.e. is yarn that stringy thing and what in the world is a crochet hook?!) and walks readers step through step. This book is mainly information though, and does not contain any patterns. It is a good reference even for expereinced crocheters.\n\nCrochet Techniques & Tips\nA much beloved guide filled with techniques, tips, and tricks explained clearly and with pictures. This book does contain information and instructions and staple stitches in every crocheters' corner. Many novice crocheters appreciate the books streight-to-the-point manner.\n\nCrochet For Beginners: A Complete Step By Step Guide With Pictures Illustrations To Learn Crocheting The Quick And Easy Way\nIf you are just starting out your crochet journey and are left handed, you will quickly find out the instructions and patterns are a bit different for you. This book contains a large section dedicated to just left-handed crocheters where others gloss over or ignore them. There are both drawings and pictures to accompany instructions and contain some patterns. This book would be best for a crocheter who has a basic knowledge of terminology and are looking to improve.\n\nThe Complete Book Of Crochet Stitch Designs: 500 Classical & Orginal Patterns\nThis book is a perfect reference guide for crocheters looking to get into more advanced stitches and designs. Each stitch comes with photo diagrams, written instructions, and use colored yarn for easy visuals. There is also information in terminology and symbols that are common in more advanced crochet. Even basic stitches are included in this book and ensure readers have a solid foundation of knowledge."
    },
    {
        id: 3, 
        title: "Where To Insert Your Hook", 
        important: "Deciding where to insert your hook has a big impact in how the resulting crochet work turns out. In some cases, pattern writers even specify where to insert one's hook.", 
        content: "\nThere are three main locations where you can insert your hook: back of the loop, front of the loop, or top of the stitch. Between stitches and post are two of the less common hook insertion points and beginners do not have to worry about those till later in their journey\n\nInserting at the top of the stitch is the default insertion location to the point where if pattern writiers don't specify a location you should assume they mean the top. You can tell the top of a stitch by looking at the top of your first row. The top of a stitch makes a '>' shape. If the stitches happen to make a '<' shape you will need to turn your work to the other side. To insert your hook through the top of a stitch, simply insert underneath the two sides of the '>' shape.\n\nLooking at the top of a stitch also helps you to tell where the front and back loops are. When looking at the stitch correctly, the front loop is the bit of stitch closest to you while the back loop is the bit of stitch farthest away from you. To insert your hook into the front loop simply insert under the front loop (disreguard the back loop) and continue on with your stitch. To insert under the back loop do the opposite; disreguard the front loop and simply insert underneath the back loop before continuting the stitch."
    }, 
    {
        id: 4, 
        title: "Single, Double, Half Double, And Triple Crochet", 
        important: "These four stitches are important becuase they help make up the foundation of crochet. These are the first stitches you will learn (after slip stitch) and a majority of patterns are comprised of them. Even advanced stitches incorporate these four stitches into their patterns.", 
        content: "\nSingle Crochet Stitch\nInsert your hook into the stitch and yarn over your hook. Then, draw your hook through the chain. Yarn over your hook again, and pull though both loops on your hook.\n\nDouble Crochet Stitch\nYarn over your hook before insertering your hook into a chain. Yarn over again and bring your hook back through the chain, you should have three loops on your hook. Yarn over again and bring your hook back through two of the loops. Finally yarn over and bring your hook through the last two loops.\n\nHalf Double Crochet Stitch\nYarn over and bring your hook through a loop. Yarn over again and bring your hook back through the loop, you should now have three loops on you hook. Finally, yarn over again and bring your hook back through all the loops on you hook.\n\nTriple (Treble) Crochet Stitch\nYarn over your hook twice before inserting the hook into a chain. Yarn over again and bring your hook back through the chain, you should now have four loops on your hook. Again yarn over, and bring your hook through the first two loops on your hook. Repeat this step twice to finish the stitch."
    }, 
    {
        id: 5, 
        title: "Scarves", 
        important: "Scarves are an excellent first project for beginners as they allow users to practice their stitches, starting new rows, changing colors, amd just get a general feel for how crocheting works.", 
        content: "\nAt its simplest, a scarf if simply repeating the same stitch over and over across multiple rows. You can of course vary your stitches and colors, but a single-stitch single-color scarf is ideal for those just starting out. Each row of a scarf usually constitutes the width of the scarf and adding another row increases the length.\n\nHere are some simple scarf patters if you need a bit of inspiration\n\nhttps://www.thesprucecrafts.com/easy-basic-crochet-scarf-pattern-979069\n\nhttps://www.hookedonhomemadehappiness.com/easy-textured-scarf/\n\nhttps://www.crochetforyoublog.com/2017/09/crochet-easy-ribbed-scarf/"
    },
    {
        id: 6, 
        title: "Small Shapes", 
        important: "Crocheting small shapres are a great way to branch out from making square or rectangular projects and improve one's pattern reading ability.", 
        content: "\nA lot of crochet shapes have what is called a magic circle as thier base. It is a good idea to master the magic cirlce as not only does it feature in small shapes but plays a role in a lot of other projects. \n\nBelow are the instructions for a magic circle.\n1) Lay your yarn out on a flat surface and make a loop in the end of your yarn\n2) Insert your hook in the middle of the circle and yarn over\n3) Draw your hook back through the circle 4)Chain one\n\nHere are some small shape patterns to get you started on your journey\n\nhttps://www.mooglyblog.com/how-to-make-5-basic-crochet-shapes-free-patterns-and-links/\n\nhttps://loopsandlovecrochet.com/2019/01/12/easy-crochet-hearts/\n\nhttps://www.stitching-together.com/simple-stars/"
    }, 
    {
        id: 7, 
        title: "Blankets", 
        important: "Blanket are a fantastic way to really practice a stitch, color changing, pattern reading, and test your endurance as a corcheter. Blankets also make an excellent gift, and there are so many different patterns and designs to choose from!", 
        content: "\nA blanket is another execellent project for beginners, though perhaps not one of the first due to the time comittment. Much like a scarf, a blanket (at its simpliest) is the same repeting stitch over and over with maybe some color changes. For a more thrilling design, there are chevron blankets, granny square blankets. and corner-to-corner blankets (which allow you to make a pixelated design). \n\nHere are a few ideas and patterns to help you get started:\n\nhttps://daisycottagedesigns.net/chevron-blanket-crochet-pattern/ \n\n https://www.thesprucecrafts.com/how-to-crochet-classic-granny-square-3576784 \n\nhttps://annabooshouse.blogspot.com/2016/11/the-enormous-squishy-blamket.html"
    }, 
    {
        id: 8, 
        title: "Where Did Crochet Come From", 
        important: "While the birth place of crochet remains unclear, having only evolved to a form we recognize today in the 1800s as it gained popularity in Europe, it is still fascinating to see how cultures around the world explored similar practices. By piecing together even a rough timeline we can get a glimpse into the past and understand how such a treasured pasttime survived the ages. It is also interesting to see the transition of crochet from being a mainly practical craft to an almost entirely leisure-based one.", 
        content: "\nTheory #1: Saudai Arabia \nThis theory suggests that crochet began in Saudai Arabia before spreading eastward to Tibet and westward to Spain and then other Mediterranean countries via trade routes.Pamir culture provides some evidence for this theory as their traditional Pamir hooks, thick and colorful socks, and overall culture are closly tied with tied with ancient Persia (a place it is theorized Arabian crochet reached due to similar evidence in the Mediterranean). Otherwise, there is little more evidence that has been popularized.\n\nTheory #2: South America\nSome of the earliest examples of crochet in South America come from adornments supposedly used in rghts of puberty. Primitve tribes where said to crochet these adornments using simple stitches. Sadly, there is not much else surviving information.\n\nTheory #3: China\nThe most common theory is that crochet spawned out of the ancient Chinese practice of tambour. Tambouring did not reach Europe intil the 1700s, and even then did not take on the name crochetuntil the end of the 18th century. Tambouring consisted of stretching a background fabric tightly over a frame. A thread is held underneath the fabric and a hooked needle is pushed through thefabric, hooked on a loop of thread, and pulled back through the fabric. Chain stitches where accomplished by working the hooked needle, with the thread loop still around it, back through the fabric father down with the new thread loop pulled through the old. It is believed the thread was very fine as surviving hooks are a similar size to sewing needles. Early examples include 3D dolls that seem to me made of crocheted stitches"
    },
    {
        id: 9, 
        title: "What Came First, Crochet Or Knitting?", 
        important: "Long story short, it is not important. Both crafts have a long and storied history, and both are fun to learn and practice. It is simply interesting to see which predates the other historically.", 
        content: '\nKnitting, But Second\nWhile it is true knitting does predate crochet, they are both late to the game compared to Nalebinding. Nalebinding is Danish of origin and can be translated to mean "binding with a needle" or "needle binding". Despite it being ancient in origin, it is still practiced today in Pero, Scandinavia, and The Balkans. Being its ancestor, Nalebinding can be mistaken for knitting despite knitting first appearng in Ancient Egypt. All in all, it is safe to say knitting came first (between just knitting and crochet).'
    },
    {
        id: 10, 
        title: "Who Crocheted?", 
        important: "Understanding who crocheted and why goes a long way to improving our understanding of crochet's evolution. It also gives us a glimpse into the past and insight into what people's lives were like.", 
        content: "\nNuns\nSome evidence point to crochet being practied by Italian nn's in the 1500s, though it was called nun's work or nun's lace rather then crochet. Some sources disagree and state that any semblance of crochet did not reach Europe intil the 18th century.\n\nHunters and Fishermen\nIn early centries hunters and fishermen would create traps and nets by knotting strands of woven fibers, cords, or cloth. This handwork was later used to create decorations for special occosions or even ceremonial costumes.\n\nThe Irish Famine\nCrochet was a huge part of the Irish potato famine, with some historians arguing it is what pulled Ireland out of the famine. Everone crocheted during this time between chores during the day and by candle by night. Men, women, and children were organized into crochet cooperatives and schools were even set up to teach the skill and train teachers. For many of the Irish, their ability to sell their crochet works abroad was what kept them alive. When many Irish citizens immifrated to America between 1845 and 1859, they brought their crochet with them (and American women quickly picked up the skill too).\n\nWomen\nBy the 1900s women were the main crocheters compared to men. They tended to crochet household items such as afghans, cushions, coffee and tea cozies, potholders, and rugs. This provided the springboard needed to make crochet the powerhouse of freeform expression it is today."
    }, 
    {
        id: 11, 
        title: "The Crochet Crowd", 
        important: "The Crochet Crowd was founded by Michael Sellick and co-creater Daniel Zondervan. Michael was inspirited to persue The Crochet Crowd to pass on his knowledge and skill as he has no children of his own. Interstingly enough, the creation of The Crochet Crowd was a bit of a fluke. Michael started out posting tutorials on YouTube, which he only began doing after being bored one afternoon adn stumbling on the site!\n\nDaniel only became invested in yarn arts and The Crochet Crowd after meeting Michael and eventually becoming his life partner. He was previously a musician, even graduating from college with a music foundation, though eventually grew out of music and left the music profession entirely.\n\nJeanne Steinhilber is another team member, joining The Crochet Crowd in 2015 after attending a crochet cruise. She was mentored by Michael who inspiried her to jump into the world of design after she learned to crochet as a child.",
        content: "\nTwitter: https://twitter.com/thecrochetcrowd\n\nInstagram: https://www.instagram.com/thecrochetcrowd/?hl=en\n\nFacebook:https://www.facebook.com/groups/TheCrochetCrowdStitchSocial\n\nYouTube: https://www.youtube.com/channel/UCVbbBdiTKMCx5VII4IKDU7A\n\nPintrest: https://pinterest.com/thecrochetcrowd", 
    }, 
    {
        id: 12, 
        title: "Moogly", 
        important: "Moogly is a corchet/knitting blog run by Tamara Kelly: designer, writier, blogger, and mother of three. Moogly originally started off as a mommy blog before transitioning into a crochet and knit business site. Eventually after Tamara realized commission work wasn't her passion, and Moogly evolved into what it is today.\n\nFun fact, according to Tamara, Moogly was a phrase coined by her daughter when she was a toddler. It is supposed to mean something 'wobbly, off-kilter, silly, or teeter-tottery'.", 
        content: "\nFacebook: https://www.facebook.com/mooglystore \n\nTwitter: https://twitter.com/intent/follow?original_referer=http%3A%2F%2Fwww.mooglyblog.com%2F&screen_name=mooglyblog&source=followbutton&variant=2.0 \n\nPintrest: https://www.pinterest.com/moogly?utm_source=creatorexp&utm_pia \n\nYouTube: https://www.youtube.com/user/mooglyblog \n\nInstagram: https://instagram.com/mooglyblog"
    }, 
    {
        id: 13, 
        title: "Bella Coco", 
        important: "Bella Coco is a blog run by Sarah-Jayne founded in 2011. The orginal focus was to share all of her passions, not just crochet. Starting in 2013 she began posting crochet tutorials on YouTube and since then has been producing new content practically every week. Staring in 2017 she partnered with lovecrochet.com to host a Bella Coco store where crocheters can shop reccomended and exclusive yarns.", 
        content: "\nFacebook: https://www.facebook.com/groups/bellacococrochetclub/ \n\nInstagram: http://www.instagram.com/bellacococrochet \n\nPintrest: http://www.pinterest.com/bellacoco86 \n\nTwitter: http://www.twitter.com/bellacocrochet \n\nYouTube: http://www.youtube.com/sa8rah56"
    }, 
    {
        id: 14, 
        title: "Creating Crochet Patterns", 
        important: "Creating crochet patterns allows you to share any of your own creations with the world! A fundamental principle of crochet is the creation, sharing, and use of patterns. As a plus, creating a pattern helps you to better understand patterns others have written.", 
        content: "\nCreating original patterns can seem difficult, but if you break the task into a few simple steps you'll have a pattern in no time!\n\n1) Practice writing out patterns you already know\n\n2) Practice writing down simple patterns from memory\n\n3) Create a very simple, very basic pattern\n\n4) Test your pattern and make any necessary improvements \n\n5) Repeat until you have a pattern you are happy with!\n\nFor more detailed guidance, check out these resources\n\nhttps://www.craftsy.com/post/how-to-create-a-crochet-pattern/\n\nhttps://www.craftsy.com/class/reading-understanding-crochet-patterns/\n\nhttps://www.craftsy.com/class/reading-understanding-crochet-patterns/"
    },
    {
        id: 15, 
        title: "Complex Stitches", 
        important: "Learning to crochet more complex stitches can be an exciting challenge! It allows you to add more flare to your projects and flex your crochet skills. As another plus, many of the prettiest crochet stitches are the more complex ones!", 
        content: "\nMany complex crochet stitches are simply made up of the basic stiches combined together to create something unique. This is why it is very important to have a sold understanding of crochet basics before moving onto complex stitches. \n\nAn excellent stitch to start with would be corner-to-corner (i.e. C2C). This stitch allows you to create a triangle by crocheting squares togehter (two triangles together makes a blanket, a common C2C project). This stitch may seem tricky at first, but after a few rows you'll be flying through them.\n\nAnother great complex stitch to start off with would be Pineapple Lace. Desite its extremely fancy looks (which some say resemble the pineapple it is named after), it is made up of some of the simplest stitches. A classic example of basic concepts coming together to form grand creations. This stitch is most commonly learned using a chart, but there are written instructions as well. \n\nThe Star Stitch is another popular choice and, like the Pineapple Lace, was named for what it resembled; a swatch of start stitches resembles a clustar of stars. It is mainly comprised of chain, slip, and half-double stitches, though tends to slant if you are not careful."
    }, 
    {
        id: 16, 
        title: "Amigurumi", 
        important: "Amigurumi is a fantastic next-step in any crochet journey if one wishes to begin challenging themselves. These figures are cute, perfect for gift giving, and enjoyable to make. THey allow crocheters to practice pattern reading, many different stitches, and a variety of other skills adn techniques.", 
        content: "\nAmigurumi comes from the Japanese terms ami and nuigurumi, ami meaning crocheted or knitted and nuigurumi meaning a stuffed doll. These figures are 3D stuffed creations that tend to be animals or fantasical creatures (though human figures are common too). Besides yarn and a crochet hook, one will also need a yarn needle, possibly a double npointed needle, filling or stuffing, and any embelishments one desires (e.g. plastic safety eyes). Before you begin your Amigurumi jounrey, get some practice in working small diameters into the round, increasing and decreasing, sewing crocheted pieces together, and reading crochet patterns, charts, or graphs."
    }, 
    {
        id: 17, 
        title: "Slip Knots, Chaining, And Slip Stitches",
        important: "Slip knots, chaining, and slip stitches are the fundamental backbone of rcohet. Without these stitches, you don't have crochet. Learning to corchet these three are some of the first steps you will take on your crochet journey. Mastering them will provide you with the foundation you need to master crochet.", 
        content: "\nSlip Knot\nHold the tail end of the yarn facing you with the working end behind it and pinch the two ends together with your middle and ring fingers, poking your index finder between the two yarn ends. Slip your corchet hook (facing updwards) between your index finger and the yarn. Twist the two ends of yarn around the hook so that the yarn makes a circle around the hook. Yarn over the hook and draw through the loop. Adjust the loop as needed.\n\nChaining\nMake a slip knot on your hook before beginning. After, yarn over and draw through the loop. This is one chain stitch. When continuing to chain, keep in mind the your tension, too much tension can result in tight, unworkable chains while not enough tension can lead to extremely lose chains.\n\nSlip Stitch\nInsert your hook into the stitch you want to slip stitch onto (note you should have a loop on your hook to begin with). Yarn over, and pull through both loops on your hook. Due to their ability to be used at any point after starting your project, slip stitches are a very useful and handy stitch. They can be used to join crocheted elements together, decorate the surface of a crocheted piece, join a round, and to form a ring."
    }
]